### ISSUE TITLE
Process a "plain old post"

### ISSUE THREAD

**Issue by chriscapaci** [UlsterPublishing/CalendarFormatter#5]
Also need the ability to process something totally different --- a plain old post. These are simple --- just title and content. Wrap the title in `<strong>` tags, content, line break. Attached is what an export for some posts looks like. 

NEED MORE INFO

[posts.csv.txt](https://github.com/UlsterPublishing/CalendarFormatter/files/425464/posts.csv.txt)

**Comment by chilthekite** [comment]
[post export all fields.txt](https://github.com/UlsterPublishing/CalendarFormatter/files/425905/post.export.all.fields.txt)
[post export limited fields.txt](https://github.com/UlsterPublishing/CalendarFormatter/files/425906/post.export.limited.fields.txt)

tribe_events, tribe_venue and tribe_organizer are all custom post types. By "plain old post" I mean the regular "post" post type. We need to be able to export those too. We just need to print the title and post_content. The attached csv was a sample export. 

The current script needs a start-time to work. In this case, we wouldn't have one. I don't know if you'd want to alter the existing formatter or make a new one on the same page. 

The export is just: `<stong>post_title</strong>post_content.` with search and replace for double space, double punctuation, &amp;, line breaks in content. No need to reference other post types like we had to with the other one to get venue address and organizer info. Only two fields, so minimal empty fields to skip. 

Attached are two different exports: one with just the header columns we're using for the post export, and one with all the header columns we use for the others.

**Comment by chriscapaci** [comment]
Hmm, since a lot of what we want to do is similar in regards to the formatting, I don't want to write a different script for it. I think the best thing would be to somehow accommodate these types of events within the current framework. I'll figure something out and let you know what I have.

**Comment by chriscapaci** [comment]
Test with a CSV containing both "tribe_event" and "post" data. I tried both separately and the script works as expected. So it's just a matter of the sort function handling those two type in the proper manner, but if there's something wrong there I'll need to fix it.

**Comment by chilthekite** [comment]
verified
